# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebed41c3a805167a8228760d59b6034f24738b3742cf39694c3a8219e863c5ad6a2b5fc8d379029dd15514361b8ab5f7de941049253caaddb90ef2bc83f8f0c5

test:
  secret_key_base: 2714810510d4a91d68d12c7b157f137c6af971aa8d5e1859f25a34729d6a68dbcef222ed5ec73eda229d07e6dd47f78d0b9403d3e7c7dc6f933490dbc9c2e87e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
